<?php
session_start();
require_once __DIR__ . '/config/database.php';
require_once __DIR__ . '/config/app.php';

// Remember Me auto-login
if (!isLoggedIn() && isset($_COOKIE['remember_token'])) {
    $token = $_COOKIE['remember_token'];
    $db = getDB();
    $stmt = $db->prepare("SELECT * FROM users WHERE remember_token = ? LIMIT 1");
    $stmt->execute([$token]);
    $user = $stmt->fetch();
    if ($user) {
        $_SESSION['user_id'] = $user['id'];
        $_SESSION['name']    = $user['name'];
        $_SESSION['role']    = $user['role'];
    }
}

$uri    = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$base   = '/food_blog';
$path   = preg_replace('#^' . preg_quote($base, '#') . '/?#', '', $uri);
$path   = preg_replace('#^index\.php/?#', '', $path);
$path   = trim($path, '/');
$parts  = explode('/', $path);
$method = $_SERVER['REQUEST_METHOD'];

$controller = $parts[0] ?: 'home';
$action     = $parts[1] ?? 'index';
$id         = $parts[2] ?? null;

// Accept clean URLs generated by the views, e.g. /restaurants/5/show.
// The original router expected /restaurants/show/5, so this makes both styles work.
if (in_array($controller, ['restaurants', 'menu-items', 'food-experience'], true)
    && isset($parts[1], $parts[2])
    && ctype_digit($parts[1])) {
    $id = $parts[1];
    $action = $parts[2];
}

// Route API calls
if ($controller === 'api') {
    $resource = $action;        // e.g. "search", "reviews", "food-exp"
    $sub      = $parts[2] ?? null;
    $apiId    = $parts[3] ?? null;
    require_once __DIR__ . '/controllers/ApiController.php';
    $api = new ApiController();
    if ($resource === 'search') $api->search();
    elseif ($resource === 'reviews') {
        if ($sub === 'add') $api->addReview();
        elseif ($sub && $apiId === null) $api->deleteReview((int)$sub); // /api/reviews/{id}
    }
    elseif ($resource === 'food-exp') {
        if ($sub === 'comments') {
            $commentAction = $parts[3] ?? null;
            if ($commentAction === 'add') $api->addComment();
            elseif ($commentAction) $api->deleteComment((int)$commentAction);
        } elseif ($sub) {
            $api->deleteFoodExpPost((int)$sub);
        }
    }
    elseif ($resource === 'admin') {
        if ($sub === 'delete-member') $api->deleteMember((int)$apiId);
        elseif ($sub === 'delete-review') $api->adminDeleteReview((int)$apiId);
        elseif ($sub === 'delete-fe-post') $api->adminDeleteFEPost((int)$apiId);
        elseif ($sub === 'delete-fe-comment') $api->adminDeleteFEComment((int)$apiId);
    }
    exit;
}

// Main routing
switch ($controller) {
    case '':
    case 'home':
        require_once __DIR__ . '/controllers/HomeController.php';
        $c = new HomeController();
        $c->index();
        break;
    case 'auth':
        require_once __DIR__ . '/controllers/AuthController.php';
        $c = new AuthController();
        match($action) {
            'register' => $c->register(),
            'login'    => $c->login(),
            'logout'   => $c->logout(),
            'profile'  => $c->profile(),
            default    => $c->login(),
        };
        break;
    case 'restaurants':
        require_once __DIR__ . '/controllers/RestaurantController.php';
        $c = new RestaurantController();
        match($action) {
            'index'   => $c->index(),
            'show'    => $c->show((int)$id),
            'create'  => $c->create(),
            'store'   => $c->store(),
            'edit'    => $c->edit((int)$id),
            'update'  => $c->update((int)$id),
            'delete'  => $c->delete((int)$id),
            default   => $c->index(),
        };
        break;
    case 'menu-items':
        require_once __DIR__ . '/controllers/MenuItemController.php';
        $c = new MenuItemController();
        match($action) {
            'show'   => $c->show((int)$id),
            'create' => $c->create(),
            'store'  => $c->store(),
            'edit'   => $c->edit((int)$id),
            'update' => $c->update((int)$id),
            'delete' => $c->delete((int)$id),
            default  => redirect('/restaurants'),
        };
        break;
    case 'food-experience':
        require_once __DIR__ . '/controllers/FoodExperienceController.php';
        $c = new FoodExperienceController();
        match($action) {
            'index'  => $c->index(),
            'show'   => $c->show((int)$id),
            'create' => $c->create(),
            'store'  => $c->store(),
            'edit'   => $c->edit((int)$id),
            'update' => $c->update((int)$id),
            'delete' => $c->delete((int)$id),
            default  => $c->index(),
        };
        break;
    case 'admin':
        require_once __DIR__ . '/controllers/AdminController.php';
        $c = new AdminController();
        match($action) {
            'dashboard' => $c->dashboard(),
            'members'   => $c->members(),
            'reviews'   => $c->reviews(),
            default     => $c->dashboard(),
        };
        break;
    default:
        http_response_code(404);
        echo '<h1>404 Not Found</h1>';
}
